import torch
import numpy as np
import random

def set_seed(seed):
    """
    Enforces deterministic execution across all random number generators.
    This guarantees that the PyTorch weight initialization and data shuffling 
    remain identical across distinct training runs for accurate A/B testing.
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

    # Disable cuDNN benchmarking to ensure perfectly reproducible CUDA kernel selection
    torch.backends.cudnn.enabled = True
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

set_seed(42)

from lib.experts.routed import SquadConfig, FeatureConfig

SYMBOL = "GBP-USD"
TIMEFRAME = "4h"
SEQ_LEN = 64

START_DATE_TRAIN = "2018-01-01"
END_DATE_TRAIN = "2022-12-31"

START_DATE_VAL = "2023-01-01"
END_DATE_VAL = "2026-03-29"

# ==============================================================================
# HIERARCHICAL ROUTING MAP & CLASS DEFINITIONS
# ==============================================================================
# The CLASS_MAP dictates the absolute dimension of the Root Router's final output tensor.
# By defining these targets explicitly, the network natively builds a multi-class classification 
# objective rather than defaulting to binary logic.
# 
# CRITICAL: `idx: 0` is strictly reserved for the 'Chop' (Null) class. The network will 
# learn to map all non-event market noise to this index, providing a safe mathematical sinkhole.
CLASS_MAP = {
    0.0:  {'idx': 0, 'squad': 'chop_squad',     'name': 'Chop'},
    1.0:  {'idx': 1, 'squad': 'detect_tops',    'name': 'Top'},
    -1.0: {'idx': 2, 'squad': 'detect_bottoms', 'name': 'Bottom'}
}
NUM_CLASSES = len(CLASS_MAP)

MODEL_DIM = 128
MODEL_EXPERTS = 8

# This specifies the exact synthetic feature column generated by the data pipeline 
# that acts as the chronological ground truth for backpropagation.
TARGET_FEATURE = "example-pivot-finder-close-2_80_all_0.005_5"

# RSI features are programmatically generated to capture a wide spectrum of momentum 
# oscillators. We intentionally disable normalization here because RSIs are inherently 
# bound between 0-100. We inject targeted Gaussian noise to prevent the network from 
# overfitting on specific smooth momentum curves.
RSI_FEATURES_CLEAN = [
    FeatureConfig(name=f"rsi-sma-normalized_{i}", normalize=False, gaussian_noise_std=0.05) 
    for i in [14, 21, 28, 35, 42, 49, 63, 70, 77, 84, 91]
]

# ==============================================================================
# MIXTURE OF EXPERTS TOPOLOGY MAP
# ==============================================================================
# This dictionary represents the physical layout of the neural tree. The `root` node 
# is the top-level macro router. It evaluates baseline momentum (RSI) to determine 
# the overarching market regime before delegating the tensor to either the `detect_tops`, 
# `detect_bottoms`, or the `chop_squad` sub-trees.
SQUADS = {
    'root': SquadConfig(
        features=[
            FeatureConfig(name="rsi-sma-normalized_14", normalize=True, gaussian_noise_std=0.01),
        ],
        model_dim=MODEL_DIM,
        seq_len=SEQ_LEN,
        routing_mode="dilated", 
        dilation_rate=8,
        fallback_squad='chop_squad',
        
        children={
            # ------------------------------------------------------------------
            # BRANCH: TOP DETECTION
            # ------------------------------------------------------------------
            'detect_tops': SquadConfig(
                routing_mode="dilated",
                dilation_rate=4,
                features=[
                    FeatureConfig(name="mcginley_34", normalize=True, gaussian_noise_std=0.01),
                ],  
                model_dim=MODEL_DIM,       
                num_experts=MODEL_EXPERTS,      
                seq_len=SEQ_LEN,
                children={
                    'rsi': SquadConfig(
                        features=RSI_FEATURES_CLEAN, 
                        model_dim=MODEL_DIM,       
                        num_experts=MODEL_EXPERTS,
                        seq_len=SEQ_LEN
                    ),
                    'indicator': SquadConfig(
                        features=[
                            FeatureConfig(name="talib-atr_14", normalize=True, gaussian_noise_std=0.01), 
                            FeatureConfig(name="talib-adx_14", normalize=False, gaussian_noise_std=0.01),
                        ],
                        model_dim=MODEL_DIM,       
                        num_experts=MODEL_EXPERTS,
                        seq_len=SEQ_LEN
                    ),
                    'candlestick': SquadConfig(
                        features=[
                            # Bearish Candlestick Reversal Patterns
                            FeatureConfig(name="talib-cdleveningstar", normalize=False),      
                            FeatureConfig(name="talib-cdleveningdojistar", normalize=False),  
                            FeatureConfig(name="talib-cdlshootingstar", normalize=False),     
                            FeatureConfig(name="talib-cdlhangingman", normalize=False),       
                            FeatureConfig(name="talib-cdlgravestonedoji", normalize=False),   
                            FeatureConfig(name="talib-cdladvanceblock", normalize=False),     
                            FeatureConfig(name="talib-cdlstalledpattern", normalize=False),   
                            FeatureConfig(name="talib-cdlidentical3crows", normalize=False),  
                            FeatureConfig(name="talib-cdlthrusting", normalize=False),        
                            FeatureConfig(name="talib-cdlengulfing", normalize=False),        
                            FeatureConfig(name="talib-cdlharami", normalize=False),           
                            FeatureConfig(name="talib-cdlharamicross", normalize=False),      
                            FeatureConfig(name="talib-cdlbelthold", normalize=False),         
                            FeatureConfig(name="talib-cdlrisefall3methods", normalize=False), 
                            FeatureConfig(name="talib-cdltasukigap", normalize=False)         
                        ],
                        model_dim=MODEL_DIM,
                        num_experts=MODEL_EXPERTS,
                        seq_len=SEQ_LEN
                    )
                }
            ),
            
            # ------------------------------------------------------------------
            # BRANCH: BOTTOM DETECTION
            # ------------------------------------------------------------------
            'detect_bottoms': SquadConfig(
                routing_mode="dilated",
                dilation_rate=4,
                features=[
                    FeatureConfig(name="mcginley_34", normalize=True, gaussian_noise_std=0.01),
                ],  
                model_dim=MODEL_DIM,
                num_experts=MODEL_EXPERTS,
                seq_len=SEQ_LEN,
                children={
                    'rsi': SquadConfig(
                        features=RSI_FEATURES_CLEAN, 
                        model_dim=MODEL_DIM,       
                        num_experts=MODEL_EXPERTS,
                        seq_len=SEQ_LEN
                    ),
                    'indicator': SquadConfig(
                        features=[
                            FeatureConfig(name="talib-atr_14", normalize=True, gaussian_noise_std=0.01), 
                            FeatureConfig(name="talib-adx_14", normalize=False, gaussian_noise_std=0.01),
                        ],
                        model_dim=MODEL_DIM,       
                        num_experts=MODEL_EXPERTS,
                        seq_len=SEQ_LEN
                    ),
                    'candlestick': SquadConfig(
                        features=[
                            # Bullish Candlestick Reversal Patterns
                            FeatureConfig(name="talib-cdlhammer", normalize=False),           
                            FeatureConfig(name="talib-cdlinvertedhammer", normalize=False),   
                            FeatureConfig(name="talib-cdlmorningstar", normalize=False),      
                            FeatureConfig(name="talib-cdlmorningdojistar", normalize=False),  
                            FeatureConfig(name="talib-cdltakuri", normalize=False),           
                            FeatureConfig(name="talib-cdldragonflydoji", normalize=False),    
                            FeatureConfig(name="talib-cdlmatchinglow", normalize=False),      
                            FeatureConfig(name="talib-cdlhomingpigeon", normalize=False),     
                            FeatureConfig(name="talib-cdlsticksandwich", normalize=False),    
                            FeatureConfig(name="talib-cdl3whitesoldiers", normalize=False),   
                            FeatureConfig(name="talib-cdlengulfing", normalize=False),        
                            FeatureConfig(name="talib-cdlharami", normalize=False),           
                            FeatureConfig(name="talib-cdlharamicross", normalize=False),      
                            FeatureConfig(name="talib-cdlbelthold", normalize=False),         
                            FeatureConfig(name="talib-cdlrisefall3methods", normalize=False), 
                            FeatureConfig(name="talib-cdltasukigap", normalize=False)         
                        ],
                        model_dim=MODEL_DIM,
                        num_experts=MODEL_EXPERTS,
                        seq_len=SEQ_LEN
                    )
                }
            ),
            
            # ------------------------------------------------------------------
            # BRANCH: CHOP SQUAD (NULL CLASS)
            # ------------------------------------------------------------------
            # Dedicated leaf node for handling non-directional sideways volatility.
            'chop_squad': SquadConfig(
                features=[
                    FeatureConfig(name="talib-adx_14", normalize=False), 
                    FeatureConfig(name="talib-atr_14", normalize=True)
                ],
                model_dim=MODEL_DIM,
                num_experts=MODEL_EXPERTS,
                seq_len=SEQ_LEN
            )
        }
    )
}

# Dynamically inject the classification requirements into the Root Node's configuration object
SQUADS['root'].class_map = CLASS_MAP
SQUADS['root'].num_classes = NUM_CLASSES

EPOCHS = 100
PATIENCE = 100

def get_expert_config():
    """
    Constructs the final, immutable ExpertConfig object to be ingested by the PyTorch model.
    It recursively calculates the exact `input_dim` for each squad based on the length 
    of its configured feature list.
    """
    from lib.experts.config import ExpertConfig, TrainingConfig

    def _set_input_dims(squads_dict):
        for k, v in squads_dict.items():
            v.input_dim = len(v.features)
            if v.children:
                _set_input_dims(v.children)

    _set_input_dims(SQUADS)

    return ExpertConfig(
        expert_id="Feature_Routed_MoE",
        model_dim=MODEL_DIM,  
        squads=SQUADS,
        training=TrainingConfig(
            # Hyperparameters derived from the latest Optuna optimization trial
            lr=0.00038713547639704615,
            weight_decay=0.01422659477874579,
            decision_threshold=0.5,
            pos_weight=1.6358219756228292,
            aux_loss_coef=0.07104187870164635
        )
    )

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")